[tool.poetry]
name = "aio-services"
version = "0.1.0"
description = ""
authors = ["Radzim Kowalow <radzim_ko@wp.pl>"]

[tool.poetry.scripts]
aio-services = "aio_services.cli:cli"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.1"
uvloop = {version = "^0.16.0", optional = true}
orjson = {version = "^3.7.1", optional = true}
nats-py = {version = "^2.1.3", optional = true}
aioredis = {version = "^2.0.1", optional = true}
aiokafka = {version = "^0.7.2", optional = true}
aio-pika = {version = "^8.0.3", optional = true}
aiorun = {version = "^2022.4.1", optional = true}
click = {version = "^8.1.3", optional = true}
[tool.poetry.extras]
all = ["orjson", "uvloop", "nats-py", "aioredis", "aiokafka", "aio-pika", "aiorun", "click"]

cli = ["aiorun", "click"]
fast = ["orjson", "uvloop"]
nats = ["nats-py"]
redis = ["aioredis"]
kafka = ["aiokafka"]
rabbitmq = ["aio-pika"]

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
mypy = "^0.960"
black = "^22.3.0"
flake8 = "^4.0.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
